version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - net

  user-service:
    build:
      dockerfile: Dockerfile
    container_name: user-service
    image: user-service
    depends_on:
      - postgres
    environment:
      CONFIG_PATH: ./local.yaml
    ports:
      - "1111:1111"
    networks:
      - net
    restart:
      always


networks:
  net:
    driver: bridge