env: "prod"
log_level: "info"
token:
  ttl: 240h
  secret: ldskjflsk;a;lk
grpc:
  port: 1111
  timeout: 1m
storage:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db: postgres