env: "local"
log_level: "debug"
token:
  ttl: 240h
  secret: ldskjflsk;a;lk
grpc:
  port: 1111
  timeout: 10h
storage:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db: postgres